### ISSUE TITLE
Being able to add service, hosts name and tags in the request.

### ISSUE THREAD

**Issue by capps1994** [DataDog/serilog-sinks-datadog-logs#7]
I have got the sink working but inside data dog it is giving me no information on where the logs are coming from and unable to filter through the logs as unable to specify the hostname, tags and service

**Comment by NBParis** [comment]
Hello @capps1994,

First of all, thanks for raising this issue and helping to improve Datadog. 

So it is indeed not provided out of the box by the sink.
This is mainly because the first version of the sink was made to give the ability to forward logs to Datadog as the mentioned feature are available with some small workarounds.

Let me explain this.
When logging in JSON (which should be the case with Serilog) you have the possibility in your Datadog pipeline to define [Reserved attribute remapping](https://docs.datadoghq.com/logs/processing/#edit-reserved-attributes) for attribute like `host` and `service`.

So if you already have a hostname or service in your JSON logs, you can remap them to the official hostname and service reserved attribute in the pipelines.

For the tags, it is a slightly different story as you would need to send the following attribute in JSON:

```
"ddtags": "key1:value1,key2:value2"
``` 

And this will automatically be added as tags.

That said, we are working on improving the sink to let you define host, service and tags at the logger definition in order to avoid specifying those attribute every time you log.

Let me know if the workaround works for you.
Thanks

**Comment by NBParis** [comment]
Hello,

This feature as been added and the Read me updated to reflect this.
Let us know if you have any questions.
